### ISSUE TITLE
内容が曖昧な状態で表示され、内容を知ろうとすると自動的にリツイートしたことになる投稿方法の提案

### ISSUE THREAD

**Issue by hakaba-hitoyo** [ryo33/Yayaka19#10]
たとえばツイッターをモデルにした邪悪なウェブアプリケーションを考えると、タイムラインのツイートがモザイクかかって表示されてて、内容を表示した瞬間にリツイートしたことになる、というのはどうか。

本当に善良な人は、拡散の共犯になることを怖れて、ここに参加することができない。また、あまりに邪悪なユーザーは、誰にもツイートを読まれなくなる。不意打ちでいきなり邪悪なツイートを拡散してしまったときは、違法性を問われたとしても、少なくとも故意犯でないことは証明できる。

https://freezepeach.xyz/notice/1571608

https://freezepeach.xyz/notice/1571614

**Comment by hakaba-hitoyo** [comment]
提案だけして実装の見込みが立っていない最悪のイシューです。

**Comment by hakaba-hitoyo** [comment]
誰にもフォローされていない捨て垢でモザイクの内容を確認する行為を撃退する必要がある。

対策として、同じログインの別垢にもモザイクが飛ぶ、フォロワーだけでなくフォロイーにもモザイクが飛ぶ、などがある。

**Comment by ryo33** [comment]
この機能で積極的に投稿したくなり、モザイクを開くことにも積極的になるようにするのはもちろんだが、モザイクを開く用のアカウントは作りたくない、というような感じになるように設計したい。「作っても意味がない」くらいだと間違えて使わないアカウントを作ってしまうのでダメで、「作りたくない」と思うくらいの強い誘因が必要。

**Comment by ryo33** [comment]
取り敢えず、モザイクを最初に見たアカウントでしか内容を表示できないという風にするだけで複垢の無効化はできるか。

**Comment by ryo33** [comment]
雑。
https://github.com/ryo33/Yayaka19/commit/b2025fb623146f5f7c93ac14d5273ae08d8464bf

**Comment by ryo33** [comment]
- [ ] 複垢対策

**Comment by hakaba-hitoyo** [comment]
[案] ミステリーポストを踏んだらフォロワーとフォロイーに全体ダメージ。
